### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zldscr0** [echarts-maps/echarts-china-cities-js#13]
请问可以用您提供的地图数据做成项目中的一部分参加比赛吗

**Comment by chfw** [comment]
只要免我的责任和不进行商用！

要商用的话，您需要和高德地图沟通。

**Comment by zldscr0** [comment]
好的，非常感谢您提供了这些宝贵的地图数据，后续如果要商用的话我会去和高德地图联系的。



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 23:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [echarts-maps/echarts-china-cities-js] question (Issue #13)




 
只要免我的责任和不进行商用！
 
要商用的话，您需要和高德地图沟通。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
