### ISSUE TITLE
能不能弄个最新的中国地图呀，十段线的·

### ISSUE THREAD

**Issue by amily4555** [echarts-maps/echarts-china-cities-js#5]
现在china.js 是九段图，可以有十段图的中国地图吗？

![image](https://user-images.githubusercontent.com/2802841/50570575-8e64be80-0dcb-11e9-836f-75e28db13649.png)

**Comment by amily4555** [comment]
![image](https://user-images.githubusercontent.com/2802841/50570577-9d4b7100-0dcb-11e9-9705-14d585d4ab67.png)

**Comment by chfw** [comment]
技术上是可以的，我得找时间画一下。

**Comment by chfw** [comment]
这里的中国地图是十段线哪，有不同么？
https://echarts-maps.github.io/echarts-china-counties-js/pages/index.html

<img width="338" alt="Screenshot 2019-05-18 at 11 59 51" src="https://user-images.githubusercontent.com/4280312/57968583-7483dc80-7964-11e9-908a-c8ebbf8afc63.png">

**Comment by chfw** [comment]
请跟踪另外一个的 issue
