### ISSUE TITLE
山东省莱芜市行政区划调整，不再设市

### ISSUE THREAD

**Issue by xinzhuang** [echarts-maps/echarts-china-cities-js#9]
山东省莱芜市调整为济南市辖区，调整为莱芜区，钢城区。需要对应调整geojson数据。
参考民政部发布的中国行政区划代码 http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201912251506.html
参考 OpenStreetMap 地图 https://www.openstreetmap.org/relation/3486449#map=9/36.7190/117.4850

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts/issues/1506
